services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    restart: no
    volumes:
      - ./api-gateway:/api-gateway
    networks:
      - dev

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: no
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - dev
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  ms-product:
    build: ./ms-product
    container_name: ms-product
    ports:
      - 8090:8090
    restart: no
    volumes:
      - ./ms-product:/ms-product
    depends_on:
      - kafka
      - postgres-ms-product
    networks:
      - dev

  postgres-ms-product:
    image: postgres
    container_name: postgres-ms-product
    ports:
      - 5432:5432
    restart: no
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres-ms-product
      POSTGRES_PASSWORD: postgres-ms-product
      POSTGRES_DB: ms-product
    volumes:
      - postgres_data_ms_product:/var/lib/postgresql/data
    networks:
      - dev

  ms-category:
    build: ./ms-category
    container_name: ms-category
    ports:
      - 8091:8091
    restart: no
    volumes:
      - ./ms-category:/ms-category
    depends_on:
      - kafka
    networks:
      - dev

networks:

  dev:
    driver: bridge

volumes:

  kafka-data:
  postgres_data_ms_product:
